services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nats-streaming:
    image: nats-streaming:0.25-alpine
    container_name: nats_streaming
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [
      "-store", "file",
      "-dir", "/datastore",
      "-m", "8222",
      "-cid", "my-cluster"
    ]
    volumes:
      - nats_data:/datastore
    networks:
      - app-network

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=myapp
      - NATS_CLUSTER_ID=my-cluster
      - NATS_CLIENT_ID=order-service
      - NATS_CHANNEL=orders
      - NATS_DURABLE_ID=order-service-durable
      - HTTP_PORT=8080
    depends_on:
      - postgres
      - nats-streaming
    networks:
      - app-network

volumes:
  postgres_data:
  nats_data:

networks:
  app-network:
    driver: bridge